name: Setup Git Identity
description: |
  Configures the Git user identity (user.name, user.email) such to allow issuing of git-commands
  that need this cfg (most prominently creating new commits).

  Existing cfg will be preserved
inputs:
  user_name:
    description: The Git user name
    required: false
    default: Gardener-CICD Bot
  user_email:
    description: The Git user email
    required: false
    default: gardener.ci.user@gmail.com
runs:
  using: composite
  steps:
    - name: Set Git user identity
      shell: bash
      run: |
        git config --global --add safe.directory $PWD
        if ! git config user.name >/dev/null; then
          git config user.name "${{ inputs.user_name }}"
        fi
        if ! git config user.email >/dev/null; then
          git config user.email "${{ inputs.user_email }}"
        fi
