name: Setup Git Identity
description: |
  Configures the Git user identity (user.name, user.email) such to allow issuing of git-commands
  that need this cfg (most prominently creating new commits).

  Existing cfg will be preserved
inputs:
  user_name:
    description: The Git user name
    required: false
    default: github-actions[bot]
  user_email:
    description: The Git user email
    required: false
    default: ''
  github_hostname:
    description: Overwrite of the GitHub hostname to determine the appropriate default GHA user
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Set Git user identity
      shell: bash
      run: |
        git config --global --add safe.directory $PWD
        if ! git config user.name >/dev/null; then
          git config user.name "${{ inputs.user_name }}"
        fi

        if ! git config user.email >/dev/null; then
          user_email=${{ inputs.user_email }}

          if [[ -z "$user_email" ]]; then
            github_host=${{ inputs.github_hostname }}

            if [[ -z "$github_host" ]]; then
              # determine user email address based on current GH-instance
              github_host="${GITHUB_SERVER_URL#https://}"
            fi

            case "$github_host" in
              github.com*)
              user_id="41898282"
              ;;
              github.tools*)
              user_id="33697"
              ;;
              github.wdf*)
              user_id="127534"
              ;;
              *)
              echo "don't know how to handle GitHub host ${github_host}"
              exit 1
              ;;
            esac

            user_email="${user_id}+github-actions[bot]@users.noreply.${github_host}"
          fi

          git config user.email "$user_email"
        fi
