name: Setup Git Identity
description: Configures the Git user identity for commits
inputs:
  user_name:
    description: The Git user name
    required: false
    default: Gardener-CICD Bot
  user_email:
    description: The Git user email
    required: false
    default: gardener.ci.user@gmail.com
runs:
  using: composite
  steps:
    - name: Set Git user identity
      shell: bash
      run: |
        git config --global --add safe.directory $PWD
        git config --global user.name "${{ inputs.user_name }}"
        git config --global user.email "${{ inputs.user_email }}"
