FROM alpine:3

# makes debugging easier
COPY ALPINE_SAP_VERSION /ALPINE_SAP_VERSION

RUN apk add --no-cache ca-certificates

ADD http://aia.pki.co.sap.com/aia/SAP%20Global%20Root%20CA.crt \
    /usr/local/share/ca-certificates/SAP_Global_Root_CA.crt
ADD http://aia.pki.co.sap.com/aia/SAPNetCA_G2.crt \
    /usr/local/share/ca-certificates/SAPNetCA_G2.crt
ADD http://aia.pki.co.sap.com/aia/SAPNetCA_G2_2.crt \
    /usr/local/share/ca-certificates/SAPNetCA_G2_2.crt
RUN update-ca-certificates
