name: component-diff
description: |
  An action to determine the component-diff between the current version (read from passed-in
  component-descriptor) and the greatest published release-version. The diff is structured according
  to `cnudie.util.ComponentDiff`.

inputs:
  component-descriptor:
    required: true
    type: string
    description: |
      An OCM-Component-Descriptor in YAML form.
  ocm-repositories:
    required: true
    type: string
    description: |
      A (comma-separated) list of ocm-repository-URLs where component-versions are to be looked up
      (order is honoured).

      Caveat: this action will only honour final versions. Hence, at least one ocm-repository
      containing final/release versions must be passed.

outputs:
  has-diff:
    description: |
      Indicates whether (at least) one of the component dependency versions has changed.
    value: ${{ steps.component-diff.outputs.has-diff }}
  component-diff:
    description: |
      The determined component diff between the current and the greatest version, structured
      according to `cnudie.util.ComponentDiff`.
    value: ${{ steps.component-diff.outputs.component-diff }}

runs:
  using: composite
  steps:
    - uses: gardener/cc-utils/.github/actions/install-gardener-gha-libs@master
    - name: Create component diff
      id: component-diff
      shell: python
      run: |
        import os
        import sys
        import textwrap

        import yaml

        import cnudie.retrieve
        import oci.client
        import ocm
        import version


        current_component_descriptor = ocm.ComponentDescriptor.from_dict(
          component_descriptor_dict=yaml.safe_load('''${{ inputs.component-descriptor}}'''),
        )
        component_name = current_component_descriptor.component.name
        component_version = current_component_descriptor.component.version

        ocm_repositories = '${{ inputs.ocm-repositories }}'.split(',')
        ocm_repository_lookup = cnudie.retrieve.ocm_repository_lookup(*ocm_repositories)

        oci_client = oci.client.client_with_dockerauth()

        component_descriptor_lookup = cnudie.retrieve.create_default_component_descriptor_lookup(
          ocm_repository_lookup=ocm_repository_lookup,
          oci_client=oci_client,
        )

        version_lookup = cnudie.retrieve.version_lookup(
          ocm_repository_lookup=ocm_repository_lookup,
          oci_client=oci_client,
        )

        greatest_version = version.greatest_version(
          versions=version_lookup(current_component_descriptor),
          ignore_prerelease_versions=True,
        )

        latest_component_descriptor = component_descriptor_lookup(
          ocm.ComponentIdentity(
            name=component_name,
            version=greatest_version,
          ),
        )

        component_diff = cnudie.retrieve.component_diff(
          left_component=latest_component_descriptor,
          right_component=current_component_descriptor,
          ignore_component_names=(component_name,),
          component_descriptor_lookup=component_descriptor_lookup,
        )

        if not component_diff:
          with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
            f.write('has-diff=false\n')

          with open(os.environ['GITHUB_STEP_SUMMARY'], 'a') as f:
            f.write(textwrap.dedent(f'''\
              ## Component-Diff

              No differences were found between current ({component_version}) and greatest release ({greatest_version}).
            '''))
            sys.exit(0)

        component_diff_str = yaml.dump(
            data=component_diff,
            Dumper=ocm.EnumValueYamlDumper,
        )

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          f.write('has-diff=true\n')
          f.write('component-diff<<EOF\n')
          f.write(component_diff_str)
          f.write('EOF\n')

        with open(os.environ['GITHUB_STEP_SUMMARY'], 'a') as f:
          f.write(textwrap.dedent(f'''\
            ## Component-Diff

            ```
            {
              '\n'.join(textwrap.indent(
                text=f'{left_c.name}: released: {left_c.version}, current: {right_c.version}',
                prefix='  ',
              ) for left_c, right_c in component_diff.cpairs_version_changed)
            }
            ```
          '''))
