name: release
description: |
  An opinionated release-Action for creating releases adhering to conventions established within
  Gardener-CICD.

  This actions assumes the version to be released is contained within passed
  OCM-Component-Descriptor. It also assumes a commit containing code-changes for said release was
  created upfront (as output by `capture-commit` action).

  Releases encompass:
  - publishing of OCM Component-Descriptor
  - pushing of a release-tag (pointing to release-commit)
  - creating of a github-release (including release-notes + release-assets)
  - pushing of "bump-commit" (to current branch)

inputs:
  component-descriptor:
    description: |
      Effective Component-Descriptor to publish. Any local-blobs are assumed to already be
      present in target-OCI-Repository.
    required: true
  component-descriptor-blobs-dir:
    description: |
      Directory containing blobfiles referenced as local-blobs in component-descriptor
      (name-scheme: <algorithm>:<hexdigest>).
    required: false
  release-commit-objects:
    description: |
      release-commit in serialised form (as output by `capture-commit` action)

      Either this input, or `release-commit-objects-artefact` must be passed.
    required: false
  release-commit-objects-artefact:
    description: |
      name of artefact (as published from capture-commit action) to use.
    required: false
  release-commit-digest:
    description: |
      release-commit-digest (necessary, unless capture-commit's special-ref is not present)
  release-commit-target:
    type: choice
    description: |
      controls where to push release-commit (and tag) to. Using `tag` option is safest, as it is
      guaranteed to succeed, also if current branch's head change during build. As release-commit
      should ideally not change (as it is referenced, e.g. in Component-Descriptor), if using
      `branch` option, merging back to current branch is attempted (instead of rebase).
      tag: push to tag (outside of current branch)
      branch: push to current branch (attempt merge if needed)
    default: tag
    options:
      - tag
      - branch
  next-version:
    type: string
    description: |
      passed to `version` action as `version-operation`. see this action for documentation
    required: false
    default: bump-minor
  next-version-commit-message:
    type: string
    description: |
      passed to `version` action as `commit-message`. see this action for documentation
    required: false
    default: 'next version: ${version}'
  next-version-callback-action-path:
    type: string
    required: false
    description: |
      passed to `version` action as `callback-action-path`
  version-read-callback:
    type: string
    description: |
      passed to `version` action as `read-callback`. see this action for documentation
    required: false
  version-write-callback:
    type: string
    description: |
      passed to `version` action as `write-callback`. see this action for documentation
    required: false
  version-versionfile:
    type: string
    description: |
      passed to `version` action as `versionfile`. see this action for documentation
  release-notes:
    description: |
      the release-notes to publish as (legacy) inline-resource in OCM-Component-Descriptor.
      Consider full-release-notes input, as well.
    required: false
  full-release-notes:
    description: |
      the release-notes to publish as body for GitHub-Release. Those should contain release-notes
      from sub-components (if any).
  github-token:
    description: |
      the github-auth-token to use for authenticating against GitHub and OCI-Registry.
      Use `secrets.GITHUB_TOKEN`
    required: true
  git-push-token:
    description: |
      an auth-token to use for pushing release- and bump-commits. Must grant the privilege to
      bypass branch-protection-rules, if present.
    required: false
  release-on-github:
    default: true
    type: boolean
    description: |
      If set to `true`, the action will create a new GitHub release (or convert an existing draft
      release to an actual release).
  assets:
    type: string
    required: false
    description: |
      An optional list of release-assets in YAML-format that will be added to the GitHub-Release.
      If creation of github-release is suppressed (via `release-on-github` input), this value
      will be ignored.

      Each element is expected to have the following form:

      ```
      name: <name, as it should be set for the release-asset>, required
      mime-type: # optional (will be determined using libmagic, if absent)
      type: ocm-resource # mandatory; only `ocm-resource` is supported; for future extensions
      id:
        name: <ocm-resource-name>, required
        type: <ocm-resource-type>, optional
        <extra-id-attr>: <value> # optional - any attributes from extraIdentity
      ```

      `id` must be specified such that a resource is identified unambiguously. Only resources
      that are stored as a localBlob (access-type) are supported.

      Example (assuming pipeline builds `helm` for multiple platforms):
      ```
      assets: |
       - name: helm-linux-x86-64
         mime-type: application/x-pie-executable
         type: ocm-resource
         id:
          name: helm
          os: linux
          arch: x86_64
      ```
  github-tag-template:
    default: '${version}'
    type: string
    description: |
      GitHub tag template to use for the created release tag. Currently only supported template-var:
      ${version} (bash-syntax): Version read from local component descriptor (i.e. previous version
      operations are honoured).
  on-existing-component-descriptor:
    default: fail
    type: choice
    description: |
      Defines how the action should behave if the (to-be-released) component-descriptor already
      exists.
    options:
      - skip
      - overwrite
      - fail
  release-notes-path:
    required: false
    type: string
    default: .ocm/release-notes
    description: |
      The relative path (from repository root) to the directory containing the release-notes docs.

outputs:
  component-descriptor:
    description: |
      the Component-Descriptor as it was published (which may contain modifications compared
      to the component-descriptor that was passed-in as input).
    value: ${{ steps.publish-component-descriptor.outputs.component-descriptor }}

defaults:
  run:
    shell: bash

runs:
  using: composite
  steps:
    - name: install-gardener-gha-libs
      uses: gardener/cc-utils/.github/actions/install-gardener-gha-libs@master
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.git-push-token || inputs.github-token }}
    - name: import-release-commit
      uses: gardener/cc-utils/.github/actions/import-commit@master
      with:
        commit-objects-artefact: ${{ inputs.release-commit-objects-artefact }}
        commit-objects: ${{ inputs.release-commit-objects }}
        commit-digest: ${{ inputs.release-commit-digest }}
        after-import: rebase
    - uses: gardener/cc-utils/.github/actions/setup-git-identity@master
    - name: preprocess
      id: preprocess
      shell: bash
      run: |
        # pass to next steps
        cat <<"EOF" > /tmp/component-descriptor.yaml
        ${{ inputs.component-descriptor }}
        EOF
        version=$(yq .component.version /tmp/component-descriptor.yaml)
        echo "version=${version}" >> $GITHUB_OUTPUT
        tag_name="${{ inputs.github-tag-template }}"
        tag_ref="refs/tags/${tag_name}"
        echo "tag-ref=${tag_ref}" >> $GITHUB_OUTPUT
        echo "tag-name=${tag_name}" >> $GITHUB_OUTPUT
        cat <<"EOF" > /tmp/assets.yaml
        ${{ inputs.assets }}
        EOF

    - name: read-target-oci-ref
      id: read-oci-ref
      shell: python
      run: |
        import os

        import yaml

        import ocm

        with open('/tmp/component-descriptor.yaml') as f:
          component_descriptor = ocm.ComponentDescriptor.from_dict(
            yaml.safe_load(f.read())
          )
        component = component_descriptor.component
        tgt_ocm_repo = component.current_ocm_repo
        tgt_oci_ref = tgt_ocm_repo.component_version_oci_ref(
          name=component.name,
          version=component.version,
        )
        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          f.write(f'ocm-target-oci-ref={tgt_oci_ref}\n')


    - name: authenticate-against-oci-registry
      uses: gardener/cc-utils/.github/actions/oci-auth@master
      with:
        oci-image-reference: ${{ steps.read-oci-ref.outputs.ocm-target-oci-ref }}
        gh-token: ${{ inputs.github-token }}

    - name: fetch-release-notes
      uses: actions/download-artifact@v4
      with:
        name: release-notes

    - name: attach-release-notes-to-component-descriptor
      shell: python
      run: |
        import dataclasses
        import hashlib
        import json

        import yaml

        import release_notes.ocm
        import oci.client
        import oci.auth
        import ocm

        with open('/tmp/component-descriptor.yaml') as f:
          component_descriptor = ocm.ComponentDescriptor.from_dict(
            yaml.safe_load(f.read())
          )
        component = component_descriptor.component
        tgt_ocm_repo = component.current_ocm_repo
        tgt_oci_ref = tgt_ocm_repo.component_version_oci_ref(
          name=component.name,
          version=component.version,
        )

        oci_client = oci.client.Client(
          credentials_lookup=oci.auth.docker_credentials_lookup(),
        )

        release_notes_markdown = '''${{ inputs.release-notes }}'''
        release_notes_octets = release_notes_markdown.encode('utf-8')
        release_notes_digest = f'sha256:{hashlib.sha256(release_notes_octets).hexdigest()}'

        oci_client.put_blob(
          image_reference=tgt_oci_ref,
          digest=release_notes_digest,
          octets_count=len(release_notes_octets),
          data=release_notes_octets,
        )

        component.resources.append(
          ocm.Resource(
            name=release_notes.ocm.release_notes_resource_name_old,
            version=component.version,
            type='text/markdown.release-notes',
            access=ocm.LocalBlobAccess(
              localReference=release_notes_digest,
              size=len(release_notes_octets),
              mediaType='text/markdown.release-notes',
            ),
          ),
        )

        with open('release-notes.tar', 'rb') as f:
          tar_bytes = f.read()
        tar_digest = f'sha256:{hashlib.sha256(tar_bytes).hexdigest()}'

        oci_client.put_blob(
          image_reference=tgt_oci_ref,
          digest=tar_digest,
          octets_count=len(tar_bytes),
          data=tar_bytes,
        )

        component.resources.append(
          ocm.Resource(
            name=release_notes.ocm.release_notes_resource_name,
            version=component.version,
            type='application/tar.release-notes',
            access=ocm.LocalBlobAccess(
              localReference=tar_digest,
              size=len(tar_bytes),
              mediaType='application/tar.release-notes',
            ),
          ),
        )

        # pass modified component-descriptor to subsequent steps
        with open('/tmp/component-descriptor.yaml', 'w') as f:
          yaml.dump(
            data=dataclasses.asdict(component_descriptor),
            Dumper=ocm.EnumValueYamlDumper,
            stream=f,
          )

    - name: publish OCM Component-Descriptor
      shell: bash
      id: publish-component-descriptor
      run: |
        python -m ocm upload \
          --file /tmp/component-descriptor.yaml \
          --blobs-dir '${{ inputs.component-descriptor-blobs-dir }}' \
          --on-exist ${{ inputs.on-existing-component-descriptor }}

        tar czf /tmp/component-descriptor.tar.gz -C/tmp component-descriptor.yaml

        echo "component-descriptor<<EOF" >> "${GITHUB_OUTPUT}"
        cat /tmp/component-descriptor.yaml >> "${GITHUB_OUTPUT}"
        echo EOF >> "${GITHUB_OUTPUT}"

    - name: upload OCM Component-Descriptor as artifact
      uses: actions/upload-artifact@v4
      with:
        path: /tmp/component-descriptor.tar.gz
        name: component-descriptor

    - name: push release-tag
      shell: bash
      run: |
        set -eu

        orig_ref="$(git rev-parse @)"
        push_spec="@:${{ steps.preprocess.outputs.tag-ref }}"
        echo "pushing release-commit using ${push_spec}"
        git push origin "${push_spec}"

        case "${{ inputs.release-commit-target }}" in
          tag)
          echo "chose to not push tag to source-branch: exiting now"
          exit 0
          ;;
          branch)
          echo "will try to push against ${{ github.ref }}"
          # fall-through (there is only error-case ahead)
          ;;
          *)
          echo "error - don't know how to handle release-commit-target:"
          echo "${{ inputs.release-commit-target }}"
          exit 1
          ;;
        esac

        # `branch`-case: we try to also push release-commit to branch that triggered us.
        #                if that fails (due to concurrent head-update), we will try to do a
        #                merge.

        push_spec="@:${{ github.ref }}"
        echo "trying to push release-commit using ${push_spec}"
        if git push origin "${push_spec}"; then
          echo "Successfully pushed release-commit to ${{ github.ref }}"
          exit 0
        fi

        version="${{ steps.preprocess.outputs.version }}"
        echo "we failed to push release-commit to ${{ github.ref }} - trying to merge"
        git fetch origin "${{ github.ref }}"
        git checkout -B "${{ github.ref_name }}" FETCH_HEAD
        if git merge "${orig_ref}" -m "merge back from release ${version}"; then
          git push origin "@:${{ github.ref }}"
          exit 0
        else
          echo "Warning: failed to merge release-commit back to ${{ github.ref }}"
          echo "release will continue as tag was successfully pushed"
          # abort merge
          rm -f .git/MERGE_HEAD
          git reset --hard FETCH_HEAD
          git checkout -B "${{ github.ref_name }}"
          # at this point, repository should have clean checkout of source-branch, pointing to
          # head-commit (discarding previous failed merge-attempt + also release-commit)
          # -> this should be okay:
          #   - tag was pushed
          #   - we still might succeed in publishing bump-commit
        fi

    - name: create github-release
      if: ${{ inputs.release-on-github }}
      shell: python
      run: |
        import os
        import sys
        sys.path.insert(1, os.environ['GITHUB_ACTION_PATH'])

        import github3
        import yaml

        import github.release
        import ocm

        import release

        host = os.environ['GITHUB_SERVER_URL'].removeprefix('https://')
        org, repo = os.environ['GITHUB_REPOSITORY'].split('/')

        token = '${{ inputs.github-token }}'
        if host == 'github.com':
          github_api = github3.GitHub(token=token)
        else:
          github_api = github3.GitHubEnterprise(
            url=f'https://{host}',
            token=token,
          )

        repository = github_api.repository(org, repo)


        release_notes_markdown = '''\
        ${{ inputs.full-release-notes }}
        '''

        release_tag_name = '${{ steps.preprocess.outputs.tag-name }}'
        draft_tag_name = f'{release_tag_name}-draft'

        if not (gh_release := github.release.find_draft_release(
          repository=repository,
          name=draft_tag_name,
        )):
          gh_release = repository.create_release(
            tag_name=release_tag_name,
            body=release_notes_markdown or 'no release-notes available',
            draft=False,
            prerelease=False,
          )
        else:
          gh_release.edit(
            tag_name=release_tag_name,
            name=release_tag_name,
            body=release_notes_markdown or 'no release-notes available',
            draft=False,
            prerelease=False,
          )

        # application/yaml is (since 2024) a registered mimetype
        # https://www.iana.org/assignments/media-types/media-types.xhtml
        gh_release.upload_asset(
          content_type='application/yaml',
          name='component-descriptor.yaml',
          asset=open('/tmp/component-descriptor.yaml'),
        )

        with open('/tmp/component-descriptor.yaml') as f:
          component_descriptor = ocm.ComponentDescriptor.from_dict(
            yaml.safe_load(f)
          )

        for asset in release.iter_assets(path='/tmp/assets.yaml'):
          path, access = release.find_blob(
            blobs_dir='${{ inputs.component-descriptor-blobs-dir }}',
            asset=asset,
            component=component_descriptor.component,
          )

          if asset.mime_type:
            mime_type = asset.mime_type
          else:
            mime_type = access.mediaType

          print(f'Uploading {asset=} as github-release-asset')
          fh = open(path, 'rb')
          gh_release.upload_asset(
            content_type=mime_type,
            name=asset.name,
            asset=fh,
          )
          fh.close() # as execution will end on errors, it should be okay to not guard against that

    - name: prepare-push-bump-commit
      shell: bash
      run: |
        # reset back to (current) head of branch for which release-job was started
        # (this will avoid merge-conflicts)
        git fetch origin "${{ github.ref }}"
        git rebase

    - name: create-bump-commit
      id: bump
      uses: gardener/cc-utils/.github/actions/version@master
      with:
        read-callback: ${{ inputs.version-read-callback }}
        write-callback: ${{ inputs.version-write-callback }}
        version-operation: ${{ inputs.next-version }}
        callback-action-path: ${{ inputs.next-version-callback-action-path }}
        prerelease: 'dev'
        commit-message: ${{ inputs.next-version-commit-message }}
        repository-operation: commit-to-head

    - name: reset-release-notes-directory
      if: ${{ inputs.release-notes-path }}
      shell: python
      run: |
        import os

        import release_notes.ocm


        release_notes.ocm.purge_release_notes_dir(
          repo_dir=os.getcwd(),
          rel_path='${{ inputs.release-notes-path }}',
        )

    - name: push-bump-commit
      shell: bash
      run: |
        if [ -n "${{ inputs.release-notes-path }}" -a -d "${{ inputs.release-notes-path }}" ]; then
          git add "${{ inputs.release-notes-path }}"
          git commit --amend --no-edit --allow-empty
        fi

        git push origin "${{ github.ref }}"
