#!/usr/bin/env sh

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

repo_dir=$(readlink -f $(dirname $0)/../..)

${repo_dir}/.ci/lint
