#!/usr/bin/env bash

set -e

if [ -z "$SOURCE_PATH" ]; then
  export SOURCE_PATH="$(readlink -f "$(dirname $0)/..")"
  echo "setting SOURCE_PATH to: ${SOURCE_PATH}"
fi

export repo_dir="${SOURCE_PATH}"

if [ ! -d "${repo_dir}" ]; then
  echo "not a directory: ${repo_dir}"
  exit 1
fi

if [ -z "$GH_PAGES_PATH" ]; then
  export GH_PAGES_PATH="${repo_dir}/documentation.out"
  mkdir -p "${GH_PAGES_PATH}"
fi

out_dir="${GH_PAGES_PATH}"

if [ ! -d ${out_dir} ]; then
  echo "not a directory: ${out_dir}"
  exit 1
fi

echo "cc-utils from: ${repo_dir}"
echo "out-dir: ${out_dir}"

export SOURCE_DIR="${repo_dir}/doc"
export OUT_DIR="${out_dir}"
export PYTHONPATH="${repo_dir}"
sphinx-build -E -a "${SOURCE_DIR}" "${OUT_DIR}"

# disable github's theme
touch "${out_dir}/.nojekyll"

# cp custom css
cp -r "${SOURCE_DIR}/css" "${OUT_DIR}/_static/"

export GIT_DIR="${OUT_DIR}/.git"
export GIT_WORK_TREE="${OUT_DIR}"

if [ -z "$(git status --porcelain=v1)" ]; then
  echo "nothing has changed - won't create a commit"
  exit 0
fi

git add .
git commit -m "update documentation"
