#!/usr/bin/env bash
set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

echo 'Running flake8 for all python modules..'
error=0

export PYTHONPATH="${src_dir}"

# ensure that all required packages are installed (useful for PRs)
echo "Making sure that packages are installed ..."
pip3 install -r "${src_dir}/requirements.txt" --quiet

echo 'running pylama for all modules (errors only)'
(
    pushd "${src_dir}"
    set -x
    if pylama -iW,R,C  -lpylint --options "${src_dir}/pylama.ini" "${src_dir}"; then
        echo 'pylama succeeded'
    else
        ((error|=1))
    fi

    if "${src_dir}/.ci/lint-flake8"; then
        echo 'pyflake8 succeeded'
    else
        ((error|=1))
    fi

    if [ $error -eq 0 ]; then
        exit 0
    elif [ $error -gt 0 ]; then
        exit 1
    fi
    popd
)

exit $?
