#!/bin/bash -e

set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

pip3 uninstall --yes flake8
pip3 install git+https://github.com/PyCQA/flake8.git

echo 'Running flake8 for all python modules..'

# flake8 / the linter it instruments cannot handle our special type-hints (CliHint)
if flake8 --ignore=F722,F821 ${src_dir}; then
    echo 'flake8 succeeded'
    exit 0
else
    echo 'flake8 found errors (see above)'
    exit 1
fi

