#!/bin/bash -e

set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"
pushd "${src_dir}"

echo 'running pycodestyle..'

if pycodestyle; then
    echo 'pycodestyle succeeded'
    popd
    exit 0
else
    echo 'Linting found errors (see above)'
    popd
    exit 1
fi

