#!/bin/bash -e

set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

echo 'running pycodestyle..'

# line lengths
echo 'checking line lengths'
if pycodestyle --select=E5 "${src_dir}"; then
    echo 'pycodestyle succeeded'
    exit 0
else
    echo 'Linting found errors (see above)'
    exit 1
fi

