#!/bin/bash -e

set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

echo 'Running pylint for all python modules..'

if pyflakes ${src_dir}/*.py ${src_dir}/**/*.py; then
    echo 'pyflakes succeeded'
    exit 0
else
    echo 'pyflakes found errors (see above)'
    exit 1
fi

