#!/bin/bash -e

set -e

# usage: $1: <src-dir>

src_dir="${1:-"$(readlink -f "$(dirname "${0}")/..")"}"

if python3 -m unittest discover --verbose --start-directory "${src_dir}" -p '*_test.py'; then
    echo 'Unittest executions succeeded'
    exit 0
else
    echo 'Errors were found whilst executing unittests (see above)'
    exit 1
fi
