#!/usr/bin/env bash

repo_root="$(dirname "${BASH_SOURCE[0]}")/.."
version=$(cat -)

versionfiles=(
  VERSION
  ci/VERSION
  oci/VERSION
  ocm/VERSION
  whd/VERSION
  cli/gardener_ci/VERSION
  concourse/resources/LAST_RELEASED_TAG
)

for fpath in "${versionfiles[@]}"; do
  echo "${version}" > "${repo_root}/${fpath}"
done
