apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: whitesource-api-extension
  namespace: {{ .Values.namespace }}
  labels:
    app: whitesource-api-extension
spec:
  schedule: "30 2 * * *"
  concurrencyPolicy: Replace
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: whitesource-api-extension
        spec:
          restartPolicy: OnFailure
          serviceAccountName: whitesource-api-extension
          containers:
          - name: whitesource-api-extension
            image: eu.gcr.io/gardener-project/cc/whitesource-api-extension:latest
            imagePullPolicy: Always
            tty: true
            ports:
            - name: web
              containerPort: 8080
              protocol: TCP
            securityContext:
              runAsUser: 0
            resources:
              requests:
                cpu: 10m
                memory: 500Mi
          terminationGracePeriodSeconds: 300
