name: Install Gardener-GHA-Libs
description: |
  Install Python3 and gardener-gha-libs

runs:
  using: composite
  steps:
    - name: install python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: install-gardener-gha-libs
      shell: bash
      run: |
        set -eu
        python3 --version
        if ! pip install gardener-gha-libs > /tmp/pip-install.log; then
          echo 'An error occured while tring to run pip install:'
          cat /tmp/pip-install.log
          exit 1
        fi
