name: capture-commit
description: |
  captures the head commit in serialised form in order to be shared w/ other jobs.

  This action is intended for the use-case of sharing a "release-commit" (where typically
  some metadata-bearing files (e.g. containing version) are modified) with other jobs, without
  persisting it, yet (as subsequent jobs might still fail).

  This action will only work if git-repository is cloned using `git` (i.e. git-repository must be
  present). It will work well if repository was cloned as `shallow`. The action needs a reference
  timestamp, which is passed via regular file. Said file *must* be created _prior_ to creating the
  commit to serialise (/"capture"). It leverages git's internal organisation of objects, where new
  objects will be created in separate files; such newly created object-files will be picked up, thus
  containing both added/changed blobs, as well as tree-objects, and commit.

  As release-commits are commonly rather small (typically just changing some versions in a few
  files), the resulting data is typically only a few kiBs in size, which allows it to be exported
  as a (base64-encoded) output (thus making passing-around somewhat less cumbersome).

  Thus-exported commits can be imported, retaining the exact same commit-digest, provided the
  importing repository has the same head-commit, into which the commit passed to this action had.

  For convenience, the commit-digest is written to hardcoded ref `refs/capture-commit` (and may
  therefore be retrieve, e.g. using `git rev-parse capture-commit`), thus allowing it to be read
  w/o the need to pass `commit-digest` from this step's outputs.

  Caveat: if more than one commit is imported, importing steps relying on said ref will have to
  guard against overwrites which will otherwise happen.

  Note: this action makes use of git-internals (mostly layout of object-db). It will only work if
  those are not violated (e.g. no git-gc or repack must be done prior to calling this action).

inputs:
  timestamp-reference:
    required: true
    description: |
      a filepath pointing to a file that was created before the head-commit
  to-artefact:
    required: false
    description: |
      if specified, the captured commits will also be uploaded as an artefact of the specified
      name. The artefact will contain a single TARchive w/ the same contents as the `commit-objects`
      output. Its name will be `commit-objects.tar.gz`
  commit-summary:
    description: |
      controls the step-summary to be emitted by this action.

      `short` will contain the changed files + commit-message
      `full`  will also contain the full diff
      `none`  will result in no summary
    default: short
    type: choice
    options:
      - short
      - full
      - none

outputs:
  commit-digest:
    description: |
      the commit-digest of the head-commit (for convenience - previous step might already know
      it, of course)
    value: ${{ steps.capture.outputs.commit-digest }}
  commit-objects:
    description: |
      a base64-encoded tarfile containing the objects required to restore the head-commit.
    value: ${{ steps.capture.outputs.commit-objects }}

runs:
  using: composite
  steps:
    - name: capture-commit
      id: capture
      run: |
        ts_ref=${{ inputs.timestamp-reference }}
        if [ ! -f ${ts_ref} ]; then
          echo "no timestamp-reference-file at expected path: ${ts_ref}"
          exit 1
        fi
        objects_out='commit-objects.tar'
        commit_out='commit-digest'
        GIT_DIR=$PWD/.git \
          ${GITHUB_ACTION_PATH}/capture-commit \
            ${objects_out} \
            ${ts_ref} \
            ${commit_out}

        tar tf ${objects_out}
        objects_size=$(stat --format=%s ${objects_out})
        objects_max_size=65536 # 64 KiB

        echo "commit-digest=$(cat ${commit_out})" >> ${GITHUB_OUTPUT}
        if [ ${objects_size} -lt ${objects_max_size} ]; then
          echo "commit-objects=$(cat ${objects_out} | base64 -w0)" >> ${GITHUB_OUTPUT}
        else
          echo "Warning: captured objects were too large (${objects_size} octets)"
          echo "commit-objects output will not be set"
        fi

        summary_kind="${{ inputs.commit-summary }}"

        if [ "${summary_kind}" == 'full' ]; then
        cat << EOF > ${GITHUB_STEP_SUMMARY}
        ## Capture-Commit Summary
        commit-digest: \`$(cat ${commit_out})\`
        objects-listing (tarfile):
        $(tar tf ${objects_out})
        commit-message:
        $(git show)
        EOF

        elif [ "${summary_kind}" == 'short' ]; then
        cat << EOF > ${GITHUB_STEP_SUMMARY}
        ## Capture-Commit Summary
        commit-digest: \`$(cat ${commit_out})\`
        objects-listing (tarfile):
        $(tar tf ${objects_out})
        EOF

        elif [ "${summary_kind}" == 'none' ]; then
          echo "will not print a summary"
        else
          echo "Error: unexpected summary-kind: ${summary_kind}"
          exit 1
        fi

        gzip ${objects_out}
      shell: bash
    - uses: gardener/cc-utils/.github/actions/upload-artifact@master
      if: ${{ inputs.to-artefact != '' }}
      with:
        name: ${{ inputs.to-artefact }}
        path: commit-objects.tar.gz
