#!/usr/bin/env python3
'''
Bundle gardener-gha-libs and its sibling packages (gardener-oci, gardener-ocm)
into a target directory for use on pinned branches.

For each package, `pip install --no-deps --target` is used to populate a
per-dist subdirectory with the package's runtime source files.  The dist name
is derived from the .dist-info directory pip creates, which is then excluded —
only source files are written.  A minimal self-contained setup.py (with
hardcoded version and install_requires from the dist metadata) is generated so
each subdirectory is pip-installable at runtime without any file lookups into
the original source tree.

Subdir names (one per package) are written to GITHUB_OUTPUT if set, and
printed to stdout.
'''

import argparse
import logging
import os
import shutil
import subprocess
import sys
import tempfile


logger = logging.getLogger(__name__)

# setup files bundled, in dependency order (oci + ocm before gha)
_SETUP_FILES = (
    'setup.oci.py',
    'setup.ocm.py',
    'setup.gha.py',
)


def _parse_dist_metadata(dist_info_dir: str) -> tuple[str, str, list[str]]:
    '''
    Parse Name, Version, and Requires-Dist from a .dist-info/METADATA file.
    Extra-only dependencies (guarded by `extra ==`) are omitted.
    '''
    name = version = None
    requires = []
    with open(os.path.join(dist_info_dir, 'METADATA')) as f:
        for line in f:
            line = line.rstrip('\n')
            if not line:
                break  # blank line ends the headers
            if line.startswith('Name: '):
                name = line[6:]
            elif line.startswith('Version: '):
                version = line[9:]
            elif line.startswith('Requires-Dist: '):
                dep = line[15:]
                if 'extra ==' not in dep:
                    requires.append(dep)
    return name, version, requires


def _gen_setup_py(name: str, version: str, install_requires: list[str]) -> str:
    '''
    Generate a minimal self-contained setup.py for a bundle subdirectory.
    Packages and py_modules are auto-discovered at install time from the
    subdirectory's own contents; no external file reads are required.
    '''
    return (
        f'# auto-generated by bundle-gardener-gha-libs; do not edit\n'
        f'import os\n'
        f'import setuptools\n'
        f'_d = os.path.abspath(os.path.dirname(__file__))\n'
        f'setuptools.setup(\n'
        f'    name={name!r},\n'
        f'    version={version!r},\n'
        f'    packages=setuptools.find_packages(_d),\n'
        f'    py_modules=[\n'
        f'        os.path.splitext(f)[0] for f in os.listdir(_d)\n'
        f'        if f.endswith(".py") and f != "setup.py"\n'
        f'    ],\n'
        f'    install_requires={install_requires!r},\n'
        f')\n'
    )


def bundle(repo_root: str, bundle_dir: str) -> list[str]:
    os.makedirs(bundle_dir, exist_ok=True)
    subdirs: list[str] = []

    for setup_file in _SETUP_FILES:
        real_setup = os.path.join(repo_root, setup_file)
        # pip install requires a directory with a setup.py, not a bare .py file.
        # Write a wrapper setup.py that chdirs to repo_root (so setuptools finds
        # the packages there) and execs the real file with its own __file__
        # (so own_dir resolves correctly inside the setup script).
        with tempfile.TemporaryDirectory(prefix='pip-src-') as src_tmp:
            with open(os.path.join(src_tmp, 'setup.py'), 'w') as f:
                f.write(
                    f'import os\n'
                    f'os.chdir({repo_root!r})\n'
                    f'_f = {real_setup!r}\n'
                    f'exec(compile(open(_f).read(), _f, "exec"), {{"__file__": _f}})\n'
                )
            with tempfile.TemporaryDirectory(prefix='pip-target-') as tmp:
                subprocess.check_call(
                    [
                        sys.executable, '-m', 'pip', 'install',
                        '--no-deps',
                        '--no-build-isolation',
                        '--target', tmp,
                        src_tmp,
                    ],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                dist_infos = [d for d in os.listdir(tmp) if d.endswith('.dist-info')]
                if not dist_infos:
                    raise RuntimeError(
                        f'pip install --target produced no .dist-info for {setup_file}'
                    )
                dist_name = dist_infos[0].split('-')[0]
                name, version, requires = _parse_dist_metadata(
                    os.path.join(tmp, dist_infos[0])
                )
                sub = os.path.join(bundle_dir, dist_name)
                shutil.copytree(tmp, sub, ignore=shutil.ignore_patterns('*.dist-info'))

        with open(os.path.join(sub, 'setup.py'), 'w') as f:
            f.write(_gen_setup_py(name, version, requires))
        subdirs.append(dist_name)
        logger.info('bundled %s -> %s', setup_file, sub)

    return subdirs


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--repo-root',
        default=os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')),
        help='path to the repository root (default: derived from script location)',
    )
    parser.add_argument(
        '--bundle-dir',
        required=True,
        help='directory to write the bundle into',
    )
    parser.add_argument('--verbose', '-v', action='store_true')
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(levelname)s %(message)s',
    )

    subdirs = bundle(args.repo_root, args.bundle_dir)

    github_output = os.environ.get('GITHUB_OUTPUT')
    if github_output:
        with open(github_output, 'a') as f:
            f.write(f'subdirs={" ".join(subdirs)}\n')

    print(' '.join(subdirs))


if __name__ == '__main__':
    main()
