#!/usr/bin/env python3
'''
Bundle gardener-gha-libs and its sibling packages (gardener-oci, gardener-ocm)
into a target directory for use on pinned branches.

For each package, `pip install --no-deps --target` is used to populate a
per-dist subdirectory with the package's runtime source files.  The dist name
is derived from the .dist-info directory pip creates, which is then excluded —
only source files are written.  A minimal self-contained setup.py (with
hardcoded version and install_requires from the dist metadata) is generated so
each subdirectory is pip-installable at runtime without any file lookups into
the original source tree.

In addition, a wheelhouse (`wheels/`) is populated with wheels for the own
dists and all their (transitive) third-party dependencies (via `pip wheel`;
sdists are built into wheels here, so no build step is needed at runtime).
Finally, a fully offline smoke-test installation is run -- a missing wheel
fails loudly here (at pin-/release-time) rather than sporadically at
action-runtime, depending on whether pypi.org happens to be reachable.

Subdir names (one per package) are written to GITHUB_OUTPUT if set, and
printed to stdout.
'''

import argparse
import logging
import os
import re
import shutil
import subprocess
import sys
import tempfile


logger = logging.getLogger(__name__)

# setup files bundled, in dependency order (oci + ocm before gha)
_SETUP_FILES = (
    'setup.oci.py',
    'setup.ocm.py',
    'setup.gha.py',
)

# own dists (never fetch from an index - wheels are built from own sources;
# namesakes on pypi.org must not end up in the wheelhouse)
_OWN_DISTS = frozenset((
    'gardener-oci',
    'gardener-ocm',
    'gardener-gha-libs',
))


def _req_name(requirement: str) -> str:
    name = re.split(r'[<>=!~;\s(\[]', requirement, maxsplit=1)[0]
    return name.strip().lower().replace('_', '-')


def _parse_dist_metadata(dist_info_dir: str) -> tuple[str, str, list[str]]:
    '''
    Parse Name, Version, and Requires-Dist from a .dist-info/METADATA file.
    Extra-only dependencies (guarded by `extra ==`) are omitted.
    '''
    name = version = None
    requires = []
    with open(os.path.join(dist_info_dir, 'METADATA')) as f:
        for line in f:
            line = line.rstrip('\n')
            if not line:
                break  # blank line ends the headers
            if line.startswith('Name: '):
                name = line[6:]
            elif line.startswith('Version: '):
                version = line[9:]
            elif line.startswith('Requires-Dist: '):
                dep = line[15:]
                if 'extra ==' not in dep:
                    requires.append(dep)
    return name, version, requires


def _collect_package_data(target_dir: str) -> dict[str, list[str]]:
    '''
    Collect non-Python data files for each Python package found under target_dir.
    Only directories containing __init__.py are considered packages.
    Returns a mapping suitable for setuptools package_data.
    '''
    result: dict[str, list[str]] = {}
    for entry in os.scandir(target_dir):
        if not entry.is_dir():
            continue
        if not os.path.isfile(os.path.join(entry.path, '__init__.py')):
            continue
        data_files = [
            f.name for f in os.scandir(entry.path)
            if f.is_file() and not f.name.endswith('.py') and not f.name.endswith('.pyc')
        ]
        if data_files:
            result[entry.name] = data_files
    return result


def _gen_setup_py(
    name: str,
    version: str,
    install_requires: list[str],
    package_data: dict[str, list[str]],
) -> str:
    '''
    Generate a minimal self-contained setup.py for a bundle subdirectory.
    Packages and py_modules are auto-discovered at install time from the
    subdirectory's own contents; no external file reads are required.
    '''
    return (
        f'# auto-generated by bundle-gardener-gha-libs; do not edit\n'
        f'import os\n'
        f'import setuptools\n'
        f'_d = os.path.abspath(os.path.dirname(__file__))\n'
        f'setuptools.setup(\n'
        f'    name={name!r},\n'
        f'    version={version!r},\n'
        f'    packages=setuptools.find_packages(_d),\n'
        f'    py_modules=[\n'
        f'        os.path.splitext(f)[0] for f in os.listdir(_d)\n'
        f'        if f.endswith(".py") and f != "setup.py"\n'
        f'    ],\n'
        f'    package_data={package_data!r},\n'
        f'    install_requires={install_requires!r},\n'
        f')\n'
    )


def _pip_env() -> dict:
    # scrub env-influences that could skew builds (e.g. egg-info visible via
    # PYTHONPATH would make pip spuriously skip "already satisfied" wheels)
    env = os.environ.copy()
    env.pop('PYTHONPATH', None)
    return env


def build_wheelhouse(
    bundle_dir: str,
    subdirs: list[str],
    requires: list[str],
    own_versions: dict[str, str],
) -> str:
    wheels_dir = os.path.join(bundle_dir, 'wheels')
    os.makedirs(wheels_dir, exist_ok=True)

    subprocess.check_call(
        [
            sys.executable, '-m', 'pip', 'wheel', '--quiet', '--no-deps',
            '--wheel-dir', wheels_dir,
            *[os.path.join(bundle_dir, sub) for sub in subdirs],
        ],
        env=_pip_env(),
    )

    reqs_file = os.path.join(bundle_dir, 'requirements-third-party.txt')
    with open(reqs_file, 'w') as f:
        f.write('\n'.join(sorted(set(requires))) + '\n')

    # setuptools + certifi: offline source for install-gardener-gha-libs'
    # install-prerequisites-on-ghe step
    subprocess.check_call(
        [
            sys.executable, '-m', 'pip', 'wheel', '--quiet',
            '--wheel-dir', wheels_dir,
            '--requirement', reqs_file,
            'setuptools',
            'certifi',
        ],
        env=_pip_env(),
    )

    # transitive deps (e.g. via odg-client -> gardener-ocm) may have pulled
    # like-named dists from pypi into the wheelhouse; pip would prefer such
    # final releases over own dev-release wheels -> purge them
    for fname in os.listdir(wheels_dir):
        if not fname.endswith('.whl'):
            continue
        dist, _, rest = fname.partition('-')
        if (norm := dist.lower().replace('_', '-')) not in _OWN_DISTS:
            continue
        if rest.split('-')[0] != own_versions[norm]:
            logger.warning('removing foreign own-dist wheel: %s', fname)
            os.remove(os.path.join(wheels_dir, fname))

    return wheels_dir


def smoke_test_wheelhouse(wheels_dir: str) -> None:
    # Prove the wheelhouse suffices for a fully offline installation, so that
    # missing wheels fail here (at pin-/release-time) rather than (sporadically)
    # depending on pypi-reachability at action-runtime.
    with tempfile.TemporaryDirectory(prefix='wheelhouse-smoke-') as target:
        env = _pip_env() | {
            'PIP_NO_INDEX': '1',
            'PIP_FIND_LINKS': wheels_dir,
        }
        subprocess.check_call(
            [
                sys.executable, '-m', 'pip', 'install', '--quiet',
                '--ignore-installed',
                '--target', target,
                *sorted(_OWN_DISTS),
            ],
            env=env,
        )


def bundle(repo_root: str, bundle_dir: str) -> list[str]:
    os.makedirs(bundle_dir, exist_ok=True)
    subdirs: list[str] = []
    all_requires: list[str] = []
    own_versions: dict[str, str] = {}

    for setup_file in _SETUP_FILES:
        real_setup = os.path.join(repo_root, setup_file)
        # pip install requires a directory with a setup.py, not a bare .py file.
        # Write a wrapper setup.py that chdirs to repo_root (so setuptools finds
        # the packages there) and execs the real file with its own __file__
        # (so own_dir resolves correctly inside the setup script).
        with tempfile.TemporaryDirectory(prefix='pip-src-') as src_tmp:
            with open(os.path.join(src_tmp, 'setup.py'), 'w') as f:
                f.write(
                    f'import os\n'
                    f'os.chdir({repo_root!r})\n'
                    f'_f = {real_setup!r}\n'
                    f'exec(compile(open(_f).read(), _f, "exec"), {{"__file__": _f}})\n'
                )
            with tempfile.TemporaryDirectory(prefix='pip-target-') as tmp:
                subprocess.check_call(
                    [
                        sys.executable, '-m', 'pip', 'install',
                        '--no-deps',
                        '--no-build-isolation',
                        '--target', tmp,
                        src_tmp,
                    ],
                    stdout=subprocess.DEVNULL,
                    stderr=subprocess.DEVNULL,
                )
                dist_infos = [d for d in os.listdir(tmp) if d.endswith('.dist-info')]
                if not dist_infos:
                    raise RuntimeError(
                        f'pip install --target produced no .dist-info for {setup_file}'
                    )
                dist_name = dist_infos[0].split('-')[0]
                name, version, requires = _parse_dist_metadata(
                    os.path.join(tmp, dist_infos[0])
                )
                all_requires.extend(requires)
                own_versions[name.lower().replace('_', '-')] = version
                sub = os.path.join(bundle_dir, dist_name)
                shutil.copytree(
                    tmp,
                    sub,
                    ignore=shutil.ignore_patterns('*.dist-info', '__pycache__', '*.pyc'),
                )

        package_data = _collect_package_data(sub)
        with open(os.path.join(sub, 'setup.py'), 'w') as f:
            f.write(_gen_setup_py(name, version, requires, package_data))
        subdirs.append(dist_name)
        logger.info('bundled %s -> %s', setup_file, sub)

    third_party = [r for r in all_requires if _req_name(r) not in _OWN_DISTS]
    wheels_dir = build_wheelhouse(bundle_dir, subdirs, third_party, own_versions)
    smoke_test_wheelhouse(wheels_dir)
    logger.info('wheelhouse populated and smoke-tested: %s', wheels_dir)

    return subdirs


def parse_args(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--repo-root',
        default=os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', '..')),
        help='path to the repository root (default: derived from script location)',
    )
    parser.add_argument(
        '--bundle-dir',
        required=True,
        help='directory to write the bundle into',
    )
    parser.add_argument('--verbose', '-v', action='store_true')
    return parser.parse_args(argv)


def main(argv=None):
    args = parse_args(argv)
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format='%(levelname)s %(message)s',
    )

    subdirs = bundle(args.repo_root, args.bundle_dir)

    github_output = os.environ.get('GITHUB_OUTPUT')
    if github_output:
        with open(github_output, 'a') as f:
            f.write(f'subdirs={" ".join(subdirs)}\n')

    print(' '.join(subdirs))


if __name__ == '__main__':
    main()
