name: upload-artifact
description: |
  a wrapper for actions/upload-artifact.

  depending on whether run on github.com, or a GHE-instance, it will dispatch to either v4 or v3
  (v4 is only available on github.com)

inputs:
  name:
    type: string
    required: true
  path:
    type: string
    required: false
  pattern:
    type: string
    required: false
    default: ''
  merge-multiple:
    type: boolean
    required: false
    default: false

runs:
  using: composite
  steps:
    - name: render
      shell: sh
      run: |
        set -eu
        if ${{ github.server_url == 'https://github.com' }}; then
          version='v4'
        else
          version='v3'
        fi

        mkdir ../upload-artifact
        "${GITHUB_ACTION_PATH}/template.sh" \
          ../upload-artifact/action.yaml \
          "${version}"
    - uses: ./../upload-artifact
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        pattern: ${{ inputs.pattern }}
        merge-multiple: ${{ inputs.merge-multiple }}
