# auto-generated by bundle-gardener-gha-libs; do not edit
import os
import setuptools
_d = os.path.abspath(os.path.dirname(__file__))
setuptools.setup(
    name='gardener-oci',
    version='1.2753.0.dev0',
    packages=setuptools.find_packages(_d),
    py_modules=[
        os.path.splitext(f)[0] for f in os.listdir(_d)
        if f.endswith(".py") and f != "setup.py"
    ],
    package_data={'oci': ['VERSION']},
    install_requires=['dacite', 'python-dateutil', 'requests', 'www-authenticate'],
)
