name: Version
description: |
  performs version-operations for release- and non-release pipelines. This action assumes version
  is kept track of within repository (either in a regular versionfile, or using callbacks). It also
  assumes versions adhere to "relaxed semver" (relaxed in that an optional v-prefix is allowed, and
  `patch` may be omitted (e.g. v1.2)).

  The action defines some defaults w.r.t versionfile/callback-lookup such to reduce amount of
  explicit configuration for convenience.

  Specifically, the following files are honoured (all paths relative to repository-root):
    - VERSION # textfile containing version
    - .ci/read-version # executable; callback (version read from stdout)
    - .ci/write-version # executable; callback (version written to stdin)

  If exactly one of `VERSION`, or `.ci/read-version`, `.ci/write-version` is present, those are
  used (without the need to set inputs accordingly). If both are present, `.ci/read-version` and
  `.ci/write-version` callbacks have precedence.

  The action will read the current version (repository-version), and calculate the "effective
  version" from it, by performing the specified `version-operation`.

  The action offers different options of how to convey created diff from  writing effective version,
  controlled via the `repository-operation`-input:

  - commit-to-head: create a commit, update head (regular result of git commit)
  - capture-commit: create a commit, but capture using `capture-commit` action (no change to head)

inputs:
  versionfile:
    required: false
    type: string
  read-callback:
    required: false
    type: string
  write-callback:
    required: false
    type: string
  version:
    required: false
    type: string
    description: |
      pass-in version for more control, if needed. versionfile/callbacks will not be used for
      reading (however, they will be used for writing). In conjunction w/ setting version-operation
      to `noop`, this allows for full control over effective-version.
  callback-action-path:
    required: false
    type: string
    description: |
      an optional path (relative to caller's repository-tree) to a GitHub-Action that is to be
      called during creation of version-commit.
      The called action can assume PWD is set to repository-root. Effective version will already
      have been written, honouring either `versionfile` or `write-callback` and chosen
      `version-operation`.

      The effective version will be passed via an input named `effective-version`. Any diff created
      by the callback-action will be included in version-commit. The callback should _not_ create
      a commit itself.

      A typical use-case for such a callback action is installation of runtime dependencies, such
      as golang-toolchain and doing code-generation using such dependencies.
  commit-message:
    required: false
    type: string
    description: |
      commit-message-template to use if the action should create a commit.
      currently only supported template-var: ${version} (bash-syntax).
    default: Set version to ${version}
  version-operation:
    required: true
    type: choice
    default: set-prerelease
    description: |
      how to calculate effective version. Possible values:
      - noop: keep version as-is (useful in conjunction w/ passing-in `version`)
      - set-prerelease: replace / set version's prerelease (e.g. 1.2.3-${prerelease})
      - bump-major: increment major-version by 1
      - bump-minor: increment minor-version by 1
      - bump-patch: increment patch-version by 1

      Note to `commit-digest-as-prelease`: The commit-digest that will be used is the one on which
      pipeline-run is based (not, e.g. the commit-digest of version-change-commit)
    options:
      - noop
      - set-prerelease
      - bump-major
      - bump-minor
      - bump-patch
  prerelease:
    required: false
    type: string
    default: ''
    description: |
      the prerelease to set. value will be interpreted as a bash-expression. The following variables
      are available (for convenience):
      - ${commit_digest} # output of `git rev-parse @`, i.e. current head's digest
      - ${epoch} # output of `rate +%s`; unix epoch in seconds

      If `noop` is set as `version-operation`, passed values are ignored.
      Setting prerelease to the empty string (which is the default) will "finalise" version.
  commit-objects-artefact:
    required: false
    type: string
    description: |
      if passed, captured commit (as output by `capture-commit` action) will (also) be uploaded
      as an artefat of the passed name.

  repository-operation:
    required: true
    type: choice
    default: capture-commit
    description: |
      Controls how to convey effective version.
      *capture-commit* (default)
      will leave repository in clean state (that is: discard _any_ changes from worktree).
      version-changing commit will be exposed using `capture-commit` action (and thus will need
      to be imported again for consumption).
      This is particularly useful if commit is to be conveyed to other jobs, with identical
      commit-digest, but without pushing the commit to upstream repository (yet).

      *commit-to-head*
      create a commit, and update head to it
    options:
      - capture-commit
      - commit-to-head

outputs:
  version:
    description: |
      the effective version
    value: ${{ steps.version.outputs.version }}
  commit-objects:
    description: |
      a base64-encoded tarfile containing the objects required to restore the version-change-commit,
      as output by capture-commit action (see for additional reference).
    value: ${{ steps.capture-commit.outputs.commit-objects }}
  commit-digest:
    description: |
      the commit-digest (as hex-string) of the created version-commit
    value: ${{ steps.capture-commit.outputs.commit-digest }}

runs:
  using: composite
  steps:
    - uses: gardener/cc-utils/.github/actions/setup-git-identity@master
    - uses: gardener/cc-utils/.github/actions/install-gardener-gha-libs@master
    - name: calculate-version
      id: calc-version
      shell: bash
      run: |
        set -eu

        touch /tmp/timestamp-ref

        # pass variables to prerelease-template
        commit_digest=$(git rev-parse @)
        epoch=$(date +%s)
        prerelease="${{ inputs.prerelease }}"

        "${GITHUB_ACTION_PATH}/version_cli.py" \
          --versionfile="${{ inputs.versionfile }}" \
          --read-callback="${{ inputs.read-callback }}" \
          --write-callback="${{ inputs.write-callback }}" \
          --root-dir="${PWD}" \
          --version="${{ inputs.version }}" \
          --operation="${{ inputs.version-operation }}" \
          --prerelease="${prerelease}" \
          --extra-version-outfile /tmp/effective-version \
          --commit-digest="${{ github.sha }}"

        echo "effective-version=$(cat /tmp/effective-version)" >> ${GITHUB_OUTPUT}

    - name: prepare-callback-action
      if: ${{ inputs.callback-action-path != '' }}
      shell: bash
      run: |
        set -eu
        # cp outside of repository-tree so we do not have to cleanup afterwards; also, we need a
        # static path, as github-actions do not allow using parameters for this
        cp -r "${{ inputs.callback-action-path }}" ../version-callback-action
    - name: call-callback-action
      if: ${{ inputs.callback-action-path != '' }}
      uses: ./../version-callback-action
      with:
        effective-version: ${{ steps.calc-version.outputs.effective-version }}

    - name: version
      id: version
      shell: bash
      run: |
        set -eu
        # expose to commit-message template
        version="$(cat /tmp/effective-version)"

        git add -A
        git commit --allow-empty -m "${{ inputs.commit-message }}"

        echo "version=${version}" >> $GITHUB_OUTPUT
        cat << EOF > ${GITHUB_STEP_SUMMARY}
        ## Version-Commit Summary
        ```
        cat $(git show)
        ```
        EOF

    - name: capture-commit
      id: capture-commit
      uses: gardener/cc-utils/.github/actions/capture-commit@master
      with:
        timestamp-reference: /tmp/timestamp-ref
        to-artefact: ${{ inputs.commit-objects-artefact }}
    - name: reset-repository
      if: ${{ inputs.repository-operation == 'capture-commit' }}
      shell: bash
      run: |
        echo "resetting (hard) worktree and index, as capture-commit was chosen"
        git reset --hard @~
        git status
