# auto-generated by bundle-gardener-gha-libs; do not edit
import os
import setuptools
_d = os.path.abspath(os.path.dirname(__file__))
setuptools.setup(
    name='gardener-ocm',
    version='1.2757.0.dev0',
    packages=setuptools.find_packages(_d),
    py_modules=[
        os.path.splitext(f)[0] for f in os.listdir(_d)
        if f.endswith(".py") and f != "setup.py"
    ],
    package_data={'ocm': ['ocm-component-descriptor-schema.yaml', 'VERSION'], 'ctt': ['README', 'simple-cfg'], 'oci': ['VERSION']},
    install_requires=['PyYaml', 'cachetools', 'cryptography', 'dacite', 'gardener-oci', 'jsonpath-ng', 'jsonschema', 'python-dateutil', 'semver'],
)
