name: Params
description: |
  An opinionated action that will emit parameters, such as OCI- and OCM-Target-Repositories, based
  on input-parameters, such as:
  - whether running on a forked repository vs. upstream
  - `mode` (snapshot vs. release)

inputs:
  mode:
    required: true
    type: choice
    default: snapshot
    options:
      - snapshot
      - release
    description: |
      "mode" will influence target-repositories to be returned.
  gh-token:
    required: true
    type: string
    description: |
      Pass-in GITHUB_TOKEN. Needs permissions to read-contents (for accessing metadata about current
      repository).
  trusted-label:
    type: string
    default: ${{ vars.DEFAULT_OK_TO_TEST_LABEL }}
    description: |
      a label that, in case of pullrequests, is considered a marker for a pullrequest to be
      trusted.
  oci-registry-prefix:
    type: string
    default: europe-docker.pkg.dev/gardener-project
    description: |
      the OCI-registry to use as prefix to calculate target OCI- and OCM-Repositories.
      depending on `mode`, `oci-registry` and `ocm-repository` outputs will be:

      ${oci-registry-prefix}/snapshots
      ${oci-registry-prefix}/releases

      `ocm-release-repository` will always have `releases` as suffix.
  snapshots-suffix:
    type: string
    default: snapshots
    description: |
      the suffix to append to oci-registry-prefix for mode `snapshot`
  releases-suffix:
    type: string
    default: releases
    description: |
      the suffix to append to oci-registry-prefix for mode `release`
  ocm-repositories:
    required: false
    type: string
    description: |
      An optional, comma-separated list of OCM-Repositories that should be used for looking-up
      OCM-Component-Versions. The OCM releases repository will always be appended to the list if
      it is not part of it yet.

outputs:
  oci-registry:
    description: |
      the OCI-Registry to use for publishing OCI-Artefacts to, considering the chosen `mode`
    value: ${{ steps.params.outputs.oci-registry }}
  ocm-repository:
    description: |
      the OCM-Repository to use for both publishing, and looking-up of OCM-Components
    value: ${{ steps.params.outputs.ocm-repository }}
  ocm-releases-repository:
    description: |
      the OCM-Repository hosting (final) release-versions (returned independent from chosen mode)
    value: ${{ steps.params.outputs.ocm-releases-repository }}
  ocm-repositories:
    description: the ocm-repositories which may be used to lookup component-versions
    value: ${{ steps.params.outputs.ocm-repositories }}
  is-fork:
    description: |
      true if current repository is a fork, else false
    value: ${{ steps.params.outputs.is-fork }}
  is-pr-from-fork:
    description: |
      true if triggering event is `pull_request`, and underlying pullrequest stems from a fork that
      does not belong to the same owner as the target repository.
    value: ${{ steps.params.outputs.is-pr-from-fork }}
  can-push:
    description: |
      boolean indicating whether or not it will likely be possible for this workflow to push
      contents (to OCI-Registries).

      If repository from which the workflow was triggered is not a fork (or a fork within the same
      organisation), pushing is always deemed possible (following cases refer to forks, only).

      If the `workflow_event` reads `pull_request`, pushing is _not_ deemded to be possible.

      If the `workflow_event` reads `pull_request_target`, pushing is possible, if the
      `author_association` of the pullrequest-event is one of `COLLABORATOR`,
      `MEMBER`, `OWNER`.

      Note that consistent usage of `cc-utils/.github/actions/trusted-checkout` is required.
      Workflows offered from cc-utils repository already do this.
    value: ${{ steps.params.outputs.can-push }}
  can-push-reason:
    description: |
      An indication (in natural language) as to why `can-push` was chosen to be either true or false.
    value: ${{ steps.params.outputs.can-push-reason }}

runs:
  using: composite
  steps:
    - id: repo-metadata
      uses: gardener/cc-utils/.github/actions/repo-metadata@master
      with:
        gh-token: ${{ inputs.gh-token }}
    - name: params
      id: params
      shell: bash
      run: |
        set -eu

        is_fork=${{ steps.repo-metadata.outputs.fork }}
        echo "repo is a fork: ${is_fork}"

        repo_prefix='${{ inputs.oci-registry-prefix }}'

        ocm_releases_repository=${repo_prefix}/${{ inputs.releases-suffix }}

        ocm_repositories='${{ inputs.ocm-repositories }}'
        if [[ ${ocm_repositories} == '' ]]; then
          ocm_repositories="${ocm_releases_repository}"
        elif [[ ${ocm_repositories} != *"${ocm_releases_repository}"* ]]; then
          ocm_repositories="${ocm_repositories},${ocm_releases_repository}"
        fi

        case "${{ inputs.mode }}" in
          snapshot)
            ocm_repository="${repo_prefix}/${{ inputs.snapshots-suffix }}"
            oci_registry="${repo_prefix}/${{ inputs.snapshots-suffix }}"
            ;;
          release)
            ocm_repository="${ocm_releases_repository}"
            oci_registry="${repo_prefix}/${{ inputs.releases-suffix }}"
            ;;
          *)
            echo "Error: unknown mode: ${{ inputs.mode }}"
            ;;
        esac

        can_push_reason='unknown'
        is_pr_from_fork=false
        event_name='${{ github.event_name }}'
        if [ ${event_name} == 'pull_request' ]; then
          repo_owner='${{ github.repository_owner }}'
          head_owner='${{ github.event.pull_request.head.repo.owner.login }}'
          if [ ${repo_owner} != ${head_owner} ]; then
            is_pr_from_fork=true
            can_push=false
            can_push_reason='untrusted fork'
          else
            is_pr_from_fork=false
            can_push=true
            can_push_reason='pullrequest from local branch'
          fi
        elif [ ${event_name} == 'pull_request_target' ]; then
          case '${{ github.event.pull_request_target.author_association }}' in
            COLLABORATOR)
              can_push=true
              can_push_reason='trusted fork'
              ;;
            MEMBER)
              can_push=true
              can_push_reason='trusted fork'
              ;;
            OWNER)
              can_push=true
              can_push_reason='trusted fork'
              ;;
            CONTRIBUTOR)
              can_push=false
              can_push_reason='untrusted fork'
              ;;
            *)
              can_push=false
              can_push_reason='untrusted fork'
          esac
          if [ '${{ github.event.action }}' == 'labeled' ] && ! $can_push; then
            if ${{ github.event.label.name == inputs.trusted-label }}; then
              can_push=true
              can_push_reason='label ${{ inputs.trusted-label }} present'
            fi
          fi
        elif [ ${event_name} == 'workflow_dispatch' ]; then
          can_push=true
          can_push_reason='run was triggered manually'
        else
          is_pr_from_fork=false
          can_push=true
          can_push_reason='unknown'
        fi
        ref='${{ github.ref }}'
        ref_leng=${#ref}
        if [ $ref_leng -gt 50 ]; then
          can_push=false # workaround: https://issuetracker.google.com/issues/264362370?pli=1
          can_push_reason='ref exceeds allowed length of 50 chars'
        fi

        echo "oci-registry=${oci_registry}" >> ${GITHUB_OUTPUT}
        echo "ocm-repository=${ocm_repository}" >> ${GITHUB_OUTPUT}
        echo "ocm-releases-repository=${ocm_releases_repository}" >> ${GITHUB_OUTPUT}
        echo "ocm-repositories=${ocm_repositories}" >> ${GITHUB_OUTPUT}
        echo "is-fork=${is_fork}" >> ${GITHUB_OUTPUT}
        echo "is-pr-from-fork=${is_pr_from_fork}" >> ${GITHUB_OUTPUT}
        echo "can-push=${can_push}" >> ${GITHUB_OUTPUT}
        echo "can-push-reason=${can_push_reason}" >> ${GITHUB_OUTPUT}

        cat << EOF > ${GITHUB_STEP_SUMMARY}
        ## Pipeline-Params-Summary

        <table> <tbody>
          <tr> <td>mode</td>            <td>${{ inputs.mode }}</td> </tr>
          <tr> <td>oci-registry</td>    <td>${oci_registry}</td> </tr>
          <tr> <td>ocm-repository</td>  <td>${ocm_repository}</td> </tr>
          <tr> <td>ocm-repositories</td><td>${ocm_repositories}</td> </tr>
          <tr> <td>is-fork</td>         <td>${is_fork}</td> </tr>
          <tr> <td>is-pr-from-fork</td> <td>${is_pr_from_fork}</td> </tr>
          <tr> <td>can-push</td>        <td>${can_push}</td> </tr>
          <tr> <td>can-push-reason</td> <td>${can_push_reason}</td> </tr>
        </tbody> </table>
        EOF
