# auto-generated by bundle-gardener-gha-libs; do not edit
import os
import setuptools
_d = os.path.abspath(os.path.dirname(__file__))
setuptools.setup(
    name='gardener-gha-libs',
    version='1.2856.0.dev0',
    packages=setuptools.find_packages(_d),
    py_modules=[
        os.path.splitext(f)[0] for f in os.listdir(_d)
        if f.endswith(".py") and f != "setup.py"
    ],
    package_data={'ctt': ['simple-cfg', 'README'], 'oci': ['VERSION'], 'ci': ['VERSION'], 'ocm': ['ocm-component-descriptor-schema.yaml', 'VERSION']},
    install_requires=['gardener-oci', 'gardener-ocm', 'GitPython', 'cachecontrol<1', 'cachetools', 'cryptography', 'dacite', 'deepmerge', 'deprecated', 'ensure', 'flake8', 'gardener-oci', 'github3.py<5.0.0', 'html2text', 'jq', 'jsonpath-ng', 'jsonschema', 'odg-client>=0.4.0', 'pycryptodome', 'pyjwt', 'pytest', 'python-dateutil', 'python-magic', 'pyyaml', 'requests', 'ruamel.yaml==0.17.21', 'semver', 'tabulate', 'termcolor', 'yamllint'],
)
