name: Build CC-Job-Image-Base
run-name: Building CC-Job-Image-Base

on:
  workflow_dispatch:

jobs:
  prepare: # required by oci-ocm-workflow
    uses: ./.github/workflows/prepare.yaml
    with:
      mode: release
  version:
    outputs:
      version: ${{ steps.version.outputs.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v5
      - name: Read Version
        id: version
        run: |
          version=$(cat JOB_IMAGE_BASE_VERSION)
          echo "version=$version" >> $GITHUB_OUTPUT

  build-and-push:
    needs:
      - prepare
      - version
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/oci-ocm.yaml
    with:
      name: job-image-base
      oci-registry: ${{ needs.prepare.outputs.oci-registry }}
      oci-repository: cicd/job-image-base
      oci-platforms: 'linux/amd64,linux/arm64'
      version: ${{ needs.version.outputs.version }}
      dockerfile: Dockerfile.job-image-base

  update-base-image-version:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      new_version: ${{ steps.update_version.outputs.new_version }}
      current_version: ${{ steps.update_version.outputs.current_version }}
    steps:
      - uses: gardener/cc-utils/.github/actions/trusted-checkout@master
        id: checkout
        with:
          auth-app-client-id: ${{ vars.GARDENER_GITHUB_ACTIONS_APP_ID }}
          auth-app-private-key: ${{ secrets.GARDENER_GITHUB_ACTIONS_PRIVATE_KEY }}

      - name: Setup Git Identity
        uses: gardener/cc-utils/.github/actions/setup-git-identity@master

      - name: Update Base Image and Increment Version
        id: update_version
        run: |
          current_version=$(cat JOB_IMAGE_BASE_VERSION)
          sed -i "s|^ARG BASE_IMAGE=.*|ARG BASE_IMAGE=ghcr.io/${{ github.repository_owner }}\
          /cc-utils/job-image-base:$current_version|" Dockerfile

          new_version=$(echo $current_version | awk -F. '{printf "%d.%d.%d", $1, $2+1, $3}')
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
          echo "current_version=$current_version" >> $GITHUB_OUTPUT
          echo "$new_version" > JOB_IMAGE_BASE_VERSION

      - name: Commit and Push Changes
        run: |
          git add Dockerfile JOB_IMAGE_BASE_VERSION
          git commit -m "Update job-image to use job-image-base \
          version ${{ steps.update_version.outputs.current_version }} \
          and prepare for ${{ steps.update_version.outputs.new_version }}"
          git checkout -b update-base-image
          git push origin update-base-image --force

      - name: Create Pull Request
        run: |
          gh pr create \
            -B master \
            -H update-base-image \
            --title "Update job-image to use version ${{ steps.update_version.outputs.current_version }}" \
            --body "Updates the job-image to use the latest job-image-base version:
              - Base Image Version: ${{ steps.update_version.outputs.current_version }}.
              - Also increments the version to ${{ steps.update_version.outputs.new_version }}."
        env:
          GITHUB_TOKEN: ${{ steps.checkout.outputs.token }}
