name: Create/Update GitHub draft-release
on:
  workflow_call:
    inputs:
      component-descriptor:
        required: true
        type: string
        description: |
          effective component-descriptor. it is sufficient to pass an incomplete
          `base component descriptor`
      ocm-repositories:
        required: true
        type: string
        description: |
          OCM-Repositories to use to lookup Component-Versions.
          Caveat: the passed repositories must yield release-versions.

jobs:
  update-draft-release:
    name: Update / Create Draft-Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: draft-release-notes
        uses: ./.github/actions/release-notes
        with:
          component-descriptor: ${{ inputs.component-descriptor }}
          ocm-repositories: ${{ inputs.ocm-repositories }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          draft: true
      - name: read-version
        id: version
        shell: bash
        run: |
          pip install yq
          version=$(
            echo "${{ inputs.component-descriptor }}" | yq .component.version
          )
          echo "version=${version}" >> ${GITHUB_OUTPUT}
          echo "version: ${version}"
      - name: update-draft-release
        uses: ./.github/actions/draft-release
        with:
          version: ${{ steps.version.outputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
