name: CI (non-release)
on:
  push:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      mode: snapshot
  component-descriptor:
    needs:
      - build-and-test
    uses: ./.github/workflows/component-descriptor.yaml
