name: CI (non-release)
on:
  push:

jobs:
  build-and-test:
    uses: ./.github/workflows/build-and-test.yaml
    with:
      mode: snapshot
    secrets: inherit
    permissions:
      contents: write
      packages: write
      id-token: write
  post-build:
    needs:
      - build-and-test
    uses: ./.github/workflows/post-build.yaml
