name: Params
description: |
  A re-usable, and strongly opinionated workflow wrapping equally-named action.
on:
  workflow_call:
    inputs:
      mode:
        required: true
        type: string
        default: snapshot
        description: |
          the "mode" to use. passed to `params` (currently for selecting  target-registries)
    outputs:
      ocm-repository:
        description: the ocm-repository to use for publishing to for the selected mode.
        value: ${{ jobs.params.outputs.ocm-repository }}
      ocm-releases-repository:
        description: the ocm-releases-repository (independent of chosen mode)
        value: ${{ jobs.params.outputs.ocm-releases-repository }}
      oci-registry:
        description: the oci-registry to use for publishing to for the selected mode
        value: ${{ jobs.params.outputs.oci-registry }}
      is-fork:
        description: boolean indicating whether or not current repository is a fork
        value: ${{ jobs.params.outputs.is-fork }}
      is-pr-from-fork:
        description: |
          boolean indicating whether or not event-trigger is from a pullrequest from
          a forked repository where fork-owner differs from origin.
        value: ${{ jobs.params.outputs.is-pr-from-fork }}

jobs:
  params:
    runs-on: ubuntu-latest
    outputs:
      ocm-repository: ${{ steps.params.outputs.ocm-repository }}
      ocm-releases-repository: ${{ steps.params.outputs.ocm-releases-repository }}
      oci-registry: ${{ steps.params.outputs.oci-registry }}
      is-fork: ${{ steps.params.outputs.is-fork }}
      is-pr-from-fork: ${{ steps.params.outputs.is-pr-from-fork }}
    steps:
      - uses: actions/checkout@v4
      - name: params
        id: params
        uses: gardener/cc-utils/.github/actions/params@master
        with:
          mode: ${{ inputs.mode }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}
