name: Test Push
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Push to refs/test/foo
        run: |
          git push origin HEAD:refs/test/foo
