name: Authenticate against k8s-API using OIDC
description: |
  An opinionated action for authenticating against Gardener-managed k8s-clusters using OIDC from
  GitHub-Action-Runs.

  For authentication to succeed, trust needs to be established from target-cluster against
  GitHub-Actions (including owner (aka org) and repository).

inputs:
  server:
    type: string
    description: |
      the endpoint serving the k8s-endpoint against which to authenticate
  server-ca:
    type: string
    description: |
      the base64-encoded certificate-bundle for the server-endpoint.
  cluster-cfg:
    type: string
    default: gardener/clusters/testmachinery-canary.yaml
    description: |
      Refers to a file located in a GitHub repository containing the k8s-api-endpoint as well as
      the k8s-api-ca. If the `server` _and_ `server-ca` inputs are specified as well, those will
      take precedence over this input parameter.

      The path must adhere to the following format: `<org>/<repo>/<path-to-file.yaml>`.

      The file is expected to have to following format:
      ```
      api: <api-url>
      ca: <base64-encoded-ca>
      ```
  audience:
    type: string
    default: gardener
    description: |
      the audience to request during OIDC-flow
  oidc-user:
    type: string
    default: gha
  kubeconfig-path:
    type: string
    default: kubeconfig.yaml
    description: |
      the path resulting kubeconfig should be generated to. If the empty string is passed,
      no kubeconfig will be written.
  service-account-name:
    type: string
    description: |
      the service account in the target-cluster to authenticate request a token for.
      It should be used by the testrunner invocation at a later stage.
  service-account-namespace:
    type: string
    description: |
      the namespace in which the service account resides.
  service-account-token-expiration:
    type: number
    default: 3600
    description: |
      the requested expiration (in seconds) of the service account token.
      Note that the actual expiration might differ, depending on the cluster's configuration.

outputs:
  kubeconfig:
    description: |
      the authenticated kubeconfig.
    value: ${{ steps.auth.outputs.kubeconfig }}

runs:
  using: composite
  steps:
    - name: prepare-cluster-cfg
      id: prepare
      if: ${{ inputs.server == '' || inputs.server-ca == '' }}
      shell: bash
      run: |
        cluster_cfg="${{ inputs.cluster-cfg }}"

        echo "repository=$(echo "${cluster_cfg}" | cut -d '/' -f1,2)" >> ${GITHUB_OUTPUT}
        echo "path=$(echo "${cluster_cfg}" | cut -d '/' -f3-)" >> ${GITHUB_OUTPUT}
    - name: checkout cluster-cfg repo
      if: ${{ inputs.server == '' || inputs.server-ca == '' }}
      uses: actions/checkout@v4
      with:
        repository: ${{ steps.prepare.outputs.repository }}
        path: ./cluster-cfg-repo
    - name: auth
      id: auth
      shell: bash
      run: |
        set -euo pipefail

        gh_token="${ACTIONS_ID_TOKEN_REQUEST_TOKEN}"
        token_url="${ACTIONS_ID_TOKEN_REQUEST_URL}"

        if [ -z "${gh_token}" -o -z ${token_url} ]; then
          echo 'Error: ACTIONS_ID_TOKEN_REQUEST_TOKEN and/or ACTIONS_ID_TOKEN_REQUEST_URL'
          echo '       were not passed'
          echo
          echo 'that typically means this workflow was not run with `id-token: write`-permission'
          exit 1
        fi

        server="${{ inputs.server }}"
        server_ca="${{ inputs.server-ca }}"

        if [ -z "${server}" -o -z ${server_ca} ]; then
          cluster_cfg_file="./cluster-cfg-repo/${{ steps.prepare.outputs.path }}"
          server=$(cat $cluster_cfg_file | yq .api)
          server_ca=$(cat $cluster_cfg_file | yq .ca)
        fi

        gha_token_url="${token_url}&audience=${{ inputs.audience }}"

        gh_auth_token=$(
          curl -sLS \
            -H "Authorization: Bearer ${gh_token}" \
            "${gha_token_url}" \
          | jq .value
        )

        if [ -z "${gh_auth_token}" ]; then
          echo 'failed to retrieve an gh-auth-token'
          exit 1
        else
          echo 'successfully retrieved an gh-auth-token'
        fi

        auth_token="${gh_auth_token}"

        if [ -n "${{ inputs.service-account-name }}" -a -n "${{ inputs.service-account-namespace }}" ]; then
          echo 'service-account details specified, requesting a service-account-token'

          echo $server_ca | base64 -d > ca.pem
          kubernetes_token_request_url="${server}/api/v1/namespaces/${{ inputs.service-account-namespace}}/serviceaccounts/${{ inputs.service-account-name}}/token"
          token_request_body='{"apiVersion":"authentication.k8s.io/v1","kind":"TokenRequest","spec":{"audiences":["kubernetes","gardener"],"expirationSeconds":${{ inputs.service-account-token-expiration}}}}'

          sa_auth_token=$(
            curl -sLS -XPOST \
              --cacert ca.pem \
              -H "Authorization: Bearer ${gh_auth_token}" \
              -H "Content-Type: application/json" \
              -H "Accept: application/json" \
              -d "${token_request_body}" \
              "${kubernetes_token_request_url}" \
            | jq -r '.status.token'
          )

          if [ -z "${sa_auth_token}" ]; then
            echo 'failed to retrieve an service account auth-token'
            exit 1
          else
            echo 'successfully retrieved an service account auth-token'
          fi

          auth_token="${sa_auth_token}"
        fi

        cat <<EOF > kubeconfig.yaml
        apiVersion: v1
        clusters:
          - name: cluster
            cluster:
              server: ${server}
              certificate-authority-data: ${server_ca}
        contexts:
          - name: gha
            context:
              cluster: cluster
              user: ${{ inputs.oidc-user }}
        current-context: gha
        kind: Config
        preferences: {}
        users:
          - name: ${{ inputs.oidc-user }}
            user:
              token: ${auth_token}
        EOF

        echo 'kubeconfig<<EOF' >> ${GITHUB_OUTPUT}
        cat kubeconfig.yaml >> ${GITHUB_OUTPUT}
        echo EOF >> ${GITHUB_OUTPUT}

        if [ -z '${{ inputs.kubeconfig-path }}' ]; then
          unlink kubeconfig.yaml
          echo 'unlinked `kubeconfig.yaml` (caller did not want it in filesystem)'
        elif [ '${{ inputs.kubeconfig-path }}' != 'kubeconfig.yaml' ]; then
          mv kubeconfig.yaml '${{ inputs.kubeconfig-path }}'
          echo 'kubeconfig can be found at `${{ inputs.kubeconfig-path }}`'
        fi
