apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-dispatcher
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhook-dispatcher
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: webhook-dispatcher
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - webhook-dispatcher
            topologyKey: kubernetes.io/hostname
      containers:
        - image: {{ .Values.image_reference }}
          imagePullPolicy: IfNotPresent
          name: webhook-dispatcher
          livenessProbe:
            tcpSocket:
              port: {{ .Values.webhook_dispatcher_port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.webhook_dispatcher_port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          command:
            - python3
            - /cc/utils/cli.py
            - whdutil
            - start_whd
            {{- range $entry := .Values.cmd_args }}
            - {{ $entry }}
            {{- end}}
            - --production
          env:
          {{- range $entry := .Values.env_vars }}
          - name: {{ index $entry "name" }}
            value: {{ index $entry "value" }}
          {{- end }}
          ports:
            - containerPort: {{ .Values.webhook_dispatcher_port }}
              name: default
      nodeSelector:
        worker.garden.sapcloud.io/group: cc-control